################################################
#                  BUILD
################################################

intel.b.pingdataconsole:
  stage: products
  script:
    - ci_scripts/build_product.sh --product pingdataconsole
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: $CUSTOM_IMAGE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingdataconsole(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingbase/**/*
        - pingdataconsole/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/pingdataconsole/*
        - helm-tests/integration-tests/**/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

arm.b.pingdataconsole:
  stage: products
  image: $RUNNER_IMAGE_AARCH64
  #image: $RUNNER_IMAGE_AARCH64_TEST
  tags:
    - platform=aarch64
  script:
    - ci_scripts/build_product.sh --product pingdataconsole
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: $CUSTOM_IMAGE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingdataconsole(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingbase/**/*
        - pingdataconsole/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/pingdataconsole/*
        - helm-tests/integration-tests/**/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

################################################
#                  SMOKE TESTS
################################################

intel.t.pingdataconsole:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product pingdataconsole
  retry: 2
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: $CUSTOM_IMAGE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip smoke\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingdataconsole(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingbase/**/*
        - pingdataconsole/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/pingdataconsole/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

arm.t.pingdataconsole:
  stage: test.smoke
  image: $RUNNER_IMAGE_AARCH64
  #image: $RUNNER_IMAGE_AARCH64_TEST
  tags:
    - platform=aarch64
  script:
    - ci_scripts/run_helm_smoke.sh --product pingdataconsole
  retry: 2
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: $CUSTOM_IMAGE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip smoke\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingdataconsole(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingbase/**/*
        - pingdataconsole/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/pingdataconsole/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

intel.t.pingdataconsole-profile:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product pingdataconsole-profile
  retry: 2
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: $CUSTOM_IMAGE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip smoke\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingdataconsole(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingbase/**/*
        - pingdataconsole/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/pingdataconsole/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

arm.t.pingdataconsole-profile:
  stage: test.smoke
  image: $RUNNER_IMAGE_AARCH64
  #image: $RUNNER_IMAGE_AARCH64_TEST
  tags:
    - platform=aarch64
  script:
    - ci_scripts/run_helm_smoke.sh --product pingdataconsole-profile
  retry: 2
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: $CUSTOM_IMAGE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip smoke\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingdataconsole(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingbase/**/*
        - pingdataconsole/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/pingdataconsole/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

################################################
#                  DEPLOY
################################################

d.pingdataconsole:
  stage: deploy
  script:
    - ci_scripts/deploy_product_to_registry.sh --product pingdataconsole
    - ci_scripts/deploy_manifests_to_registry.sh --product pingdataconsole
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: $CUSTOM_IMAGE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip deploy\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingdataconsole(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$PING_IDENTITY_SNAPSHOT =~ /--snapshot/'
      when: never
    - if: '$CI_COMMIT_REF_NAME =~ /^master$/'
      changes:
        - pingdataconsole/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_COMMIT_TAG =~ /^\d{4}\.?\d*/'
      when: on_success
