sudo: required
branches:
  only:
  - gh-pages
  - "/.*/"
services:
- docker
before_install:
- chmod +x ./ci_scripts/if_readme_only.sh
- "./ci_scripts/if_readme_only.sh"
script:
- docker image build -t pingidentity/pingdatacommon ./pingdatacommon
- docker-compose -f ./pingdirectory/build.test.yml up
- docker image build -t samirgandhi/pingfederate ./pingfederate
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push samirgandhi/pingfederate
notifications:
  slack:
    secure: FCRt7hhbn8krX/zMZrFnz9lETT/I9Dt5QcDnmkSPv85f7atlangA13EXYhZUaj69Y1mdpJvacCit/HYTlKXrqVZO0swqScXh1sxYxFFZAOtYZSbK9gBES+CCtR3T9WHDyF2f0IDdvlO+ZyaLpcefaQ6/KaraoxmYtFmsMrzjUBJNXabyIr0ps7EUVTz1nejfqZvIhd3w5OZPQHmaHIVQdjQF5LLGFBuzCClfRziwhkhpZg4aG/t/fimWO/kz5UophGjv2ljCgNe9acKdjVi4Xx5WJRkdAIfPgr/PMOf5v/6DL7278knLOMig8A/JPJKtr1jvPdtH3DCygfDQBsK28Zf6/rMnNrTDH/9qPQ3eMUc15pzaZ2N2JLRtTZuhvrh2vfpPDVT14vDgMebvWRCn3Wyu6Rmj/yN9v+HNbSmxMzcRqu/TaADx8zACDkqA7gRZH9P+9rot0//WwsathKOZdCk3kv4lDic6bGvBxBqYCZgmXEoyTijWbTf2GJNExh19/ydAl5ZAdGmwjDvnNzlU5/C54YRo0wNCy3OiiZQgHX/Ds3ADIexiRLq4NWvSFaLcfBsOMuI3Y8P8k2FIYLCMubPdd2Ya/vZABEN/pBioIOV5oDKWzCzo8RuUn89ZNmmqfQTBBAJi6uXOpC1YrHvecjR38ht1B5t/paSu9Stt4Xo=
