################################################
#                  BUILD
################################################

intel.b.pingaccess:
  stage: products
  script:
    - ci_scripts/build_product.sh --product pingaccess
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingaccess(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingbase/**/*
        - pingaccess/**/*
        - pingdirectory/**/*
        - pingintelligence/**/*
        - pingfederate/**/*
        - integration_tests/**/*
        - pingjvm/*
        - ci_scripts/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/pingaccess/*
        - helm-tests/integration-tests/**/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

arm.b.pingaccess:
  stage: products
  image: $RUNNER_IMAGE_AARCH64
  tags:
    - platform=aarch64
  script:
    - ci_scripts/build_product.sh --product pingaccess
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingaccess(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingbase/**/*
        - pingaccess/**/*
        - pingdirectory/**/*
        - pingintelligence/**/*
        - pingfederate/**/*
        - integration_tests/**/*
        - pingjvm/*
        - ci_scripts/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/pingaccess/*
        - helm-tests/integration-tests/**/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

################################################
#                  SMOKE TESTS
################################################

intel.t.pingaccess:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product pingaccess
  retry: 2
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip smoke\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingaccess(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingbase/**/*
        - pingaccess/**/*
        - pingjvm/*
        - ci_scripts/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/pingaccess/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

arm.t.pingaccess:
  stage: test.smoke
  image: $RUNNER_IMAGE_AARCH64
  tags:
    - platform=aarch64
  script:
    - ci_scripts/run_helm_smoke.sh --product pingaccess
  retry: 2
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip smoke\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingaccess(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingbase/**/*
        - pingaccess/**/*
        - pingjvm/*
        - ci_scripts/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/pingaccess/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

intel.t.pingaccess-cluster:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product pingaccess-cluster
  retry: 2
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip smoke\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingaccess(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingbase/**/*
        - pingaccess/**/*
        - pingjvm/*
        - ci_scripts/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/pingaccess/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

arm.t.pingaccess-cluster:
  stage: test.smoke
  image: $RUNNER_IMAGE_AARCH64
  tags:
    - platform=aarch64
  script:
    - ci_scripts/run_helm_smoke.sh --product pingaccess-cluster
  retry: 2
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip smoke\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingaccess(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingbase/**/*
        - pingaccess/**/*
        - pingjvm/*
        - ci_scripts/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/pingaccess/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

################################################
#                  DEPLOY
################################################

d.pingaccess:
  stage: deploy
  script:
    - ci_scripts/deploy_product_to_registry.sh --product pingaccess
    - ci_scripts/deploy_manifests_to_registry.sh --product pingaccess
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip deploy\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingaccess(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$PING_IDENTITY_SNAPSHOT =~ /--snapshot/'
      when: never
    - if: '$CI_COMMIT_REF_NAME =~ /^master$/'
      changes:
        - pingaccess/**/*
        - pingcommon/**/*
        - pingbase/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_COMMIT_TAG =~ /^\d{4}\.?\d*/'
      when: on_success
