################################################
#                  BUILD
################################################

intel.b.pingauthorize:
  stage: products
  script:
    - ci_scripts/build_product.sh --product pingauthorize
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingauthorize(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - pingauthorize/**/*
        - pingdirectory/**/*
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingbase/**/*
        - integration_tests/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/pingauthorize/*
        - helm-tests/integration-tests/**/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

arm.b.pingauthorize:
  stage: products
  image: $RUNNER_IMAGE_AARCH64
  tags:
    - platform=aarch64
  script:
    - ci_scripts/build_product.sh --product pingauthorize
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingauthorize(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - pingauthorize/**/*
        - pingdirectory/**/*
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingbase/**/*
        - integration_tests/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/pingauthorize/*
        - helm-tests/integration-tests/**/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

################################################
#                  SMOKE TESTS
################################################

intel.t.pingauthorize:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product pingauthorize
  retry: 2
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip smoke\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingauthorize(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingbase/**/*
        - pingauthorize/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/pingauthorize/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

arm.t.pingauthorize:
  stage: test.smoke
  image: $RUNNER_IMAGE_AARCH64
  tags:
    - platform=aarch64
  script:
    - ci_scripts/run_helm_smoke.sh --product pingauthorize
  retry: 2
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip smoke\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingauthorize(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingbase/**/*
        - pingauthorize/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/pingauthorize/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

################################################
#                  DEPLOY
################################################

d.pingauthorize:
  stage: deploy
  script:
    - ci_scripts/deploy_product_to_registry.sh --product pingauthorize
    - ci_scripts/deploy_manifests_to_registry.sh --product pingauthorize
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip deploy\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingauthorize(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$PING_IDENTITY_SNAPSHOT =~ /--snapshot/'
      when: never
    - if: '$CI_COMMIT_REF_NAME =~ /^master$/'
      changes:
        - pingauthorize/**/*
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingbase/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_COMMIT_TAG =~ /^\d{4}$/'
      when: on_success
